version: '3.7'
services:
  nginx:
    image: nginx:latest
    #container_name: nginx1
    networks:
      - wan
    volumes:
      - ./www:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.site1http.rule=Host(`site1.domain.lan`)
      - traefik.http.routers.site1http.entrypoints=http

      - traefik.http.routers.site1http.middlewares=redirect@file

      - traefik.http.routers.site1https.tls=true
      - traefik.http.routers.site1https.entrypoints=https
      - traefik.http.routers.site1https.rule=Host(`site1.domain.lan`)

# Enregistrer une route en HTTP
      #- traefik.enable=true
      #- traefik.http.routers.site1.entryPoints=http
      #- traefik.http.routers.site1.rule=Host(`site1.domain.lan`)

# Enregistrer une route en HTTPS. Obliger de configurer HTTP avant.
      #- traefik.enable=true
      #- traefik.http.routers.site1-http.entrypoints=http
      #- traefik.http.routers.site1-http.rule=Host(`site1.domain.lan`)
      #- traefik.http.routers.site1-https.tls=true
      #- traefik.http.routers.site1-https.entrypoints=https
      #- traefik.http.routers.site1-https.rule=Host(`site1.domain.lan`)

# Forcer à utiliser HTTPS
      #- traefik.enable=true
      #- traefik.http.routers.site1-http.entrypoints=http
      #- traefik.http.routers.site1-http.rule=Host(`site1.domain.lan`)
      #- traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      #- traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      #- traefik.http.routers.site1-http.middlewares=https-redirect@docker
      #- traefik.http.routers.site1-https.tls=true
      #- traefik.http.routers.site1-https.entrypoints=https
      #- traefik.http.routers.site1-https.rule=Host(`site1.domain.lan`)

networks:
  wan:
    external: true


# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
